Pustok/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Pustok.DAL;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using Pustok.ViewModels.Basket;
using Newtonsoft.Json;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Pustok.Controllers
{
    public class BasketController : Controller
    {
        private readonly AppDbContext _context;
        public BasketController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            string basket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (basket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            foreach (BasketVM basketVM in basketVMs)
            {
                basketVM.Title = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Title;
                basketVM.MainImage = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).MainImage;
                basketVM.Price = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Price;
            }


            return View(basketVMs);
        }

        public IActionResult GetBasket()
        {
            string basket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (basket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            foreach (BasketVM basketVM in basketVMs)
            {
                basketVM.Title = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Title;
                basketVM.MainImage = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).MainImage;
                basketVM.Price = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Price;
                basketVM.GenreName = _context.Products.Include(p => p.Genre).FirstOrDefault(p => p.Id == basketVM.Id).Genre.Name;
            }


            return PartialView("_BasketPartial", basketVMs);
        }

        public IActionResult GetTotalSum()
        {
            string basket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (basket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            foreach (BasketVM basketVM in basketVMs)
            {
                basketVM.Title = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Title;
                basketVM.MainImage = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).MainImage;
                basketVM.Price = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Price;
                basketVM.GenreName = _context.Products.Include(p => p.Genre).FirstOrDefault(p => p.Id == basketVM.Id).Genre.Name;
            }


            return PartialView("_BasketTotalSumPartial", basketVMs);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();

            if (!await _context.Products.AnyAsync(p => p.Id == id)) return NotFound();

            List<BasketVM> basketVMs = null;

            string coockie = HttpContext.Request.Cookies["basket"];

            if(coockie != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(coockie);

                if (!basketVMs.Any(b => b.Id == id)) return NotFound();

                BasketVM basketVM = basketVMs.FirstOrDefault(b => b.Id == id);

                basketVMs.Remove(basketVM);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            coockie = JsonConvert.SerializeObject(basketVMs);

            HttpContext.Response.Cookies.Append("basket",coockie);

            foreach (BasketVM basketVM in basketVMs)
            {
                basketVM.Title = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Title;
                basketVM.MainImage = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).MainImage;
                basketVM.Price = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Price;
                basketVM.GenreName = _context.Products.Include(p => p.Genre).FirstOrDefault(p => p.Id == basketVM.Id).Genre.Name;
            }


            return PartialView("_BasketProductTablePartial", basketVMs);
        }
    }
}

Pustok/Views/Shared/_BasketPartial.cshtml
@model List<BasketVM>
<div class="cart-total">
                                            <span class="text-number">
                                                @Model.Count
                                            </span>
                                            <span class="text-item">
                                                Shopping Cart
                                            </span>
                                            <span class="price">
                                                @{
                                                    double total = 0;

                                                    foreach (BasketVM basketVM in Model)
                                                    {
                                                        total += (basketVM.Count * basketVM.Price);
                                                    }
                                                }

                                                £@total.ToString("F2")
                                                <i class="fas fa-chevron-down"></i>
                                            </span>
                                        </div>
                                        <div class="cart-dropdown-block">
                                            @foreach (BasketVM basketVM in Model)
                                            {
                                                <div class=" single-cart-block ">
                                                <div class="cart-product">
                                                    <a href="~/product-details.html" class="image">
                                                        <img src="~/image/products/@basketVM.MainImage" alt="">
                                                    </a>
                                                    <div class="content">
                                                        <h3 class="title">
                                                            <a href="~/product-details.html">
                                                                @basketVM.GenreName @basketVM.Title
                                                            </a>
                                                        </h3>
                                                        <p class="price"><span class="qty">@basketVM.Count ×</span> £@basketVM.Price.ToString("F2")</p>
                                                        <button class="cross-btn"><i class="fas fa-times"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                            }
                                            <div class=" single-cart-block ">
                                                <div class="btn-block">
                                                    <a asp-controller="Basket" asp-action="Index" class="btn">
                                                        View Cart <i class="fas fa-chevron-right"></i>
                                                    </a>
                                                    <a href="~/checkout.html" class="btn btn--primary">
                                                        Check Out <i class="fas fa-chevron-right"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>

Pustok/Views/Shared/_BasketProductTablePartial.cshtml
@model List<BasketVM>
@foreach (BasketVM basketVM in Model)
										   {
											   <!-- Product Row -->
											<tr>
												<td class="pro-remove"><a class="deleteproduct" asp-controller="Basket" asp-action="Delete" asp-route-id="@basketVM.Id"><i class="far fa-trash-alt"></i></a>
												</td>
												<td class="pro-thumbnail"><a href="#"><img
															src="image/products/@basketVM.MainImage" alt="Product"></a></td>
												<td class="pro-title"><a href="#">Rinosin Glasses</a></td>
												<td class="pro-price"><span>$@basketVM.Price.ToString("F2")</span></td>
												<td class="pro-quantity">
													<div class="pro-qty">
														<div class="count-input-block">
															<input type="number" data-productId="@basketVM.Id" class="form-control text-center productcount"
																value="@basketVM.Count">
														</div>
													</div>
												</td>
												<td class="pro-subtotal"><span>$@((basketVM.Count * basketVM.Price).ToString("F2"))</span></td>
											</tr>
										   }
										   <tr>
												<td colspan="6" class="actions">
													<div class="coupon-block">
														<div class="coupon-text">
															<label for="coupon_code">Coupon:</label>
															<input type="text" name="coupon_code" class="input-text"
																id="coupon_code" value="" placeholder="Coupon code">
														</div>
														<div class="coupon-btn">
															<input type="submit" class="btn btn-outlined"
																name="apply_coupon" value="Apply coupon">
														</div>
													</div>
													<div class="update-block text-right">
														<input type="submit" class="btn btn-outlined" name="update_cart"
															value="Update cart">
														<input type="hidden" id="_wpnonce" name="_wpnonce"
															value="05741b501f"><input type="hidden"
															name="_wp_http_referer" value="/petmark/cart/">
													</div>
												</td>
											</tr>

Pustok/Views/Shared/_BasketTotalSumPartial.cshtml
<h4><span>Cart Summary</span></h4>
@model List<BasketVM>

@{
                                                    double total = 0;

                                                    foreach (BasketVM basketVM in Model)
                                                    {
                                                        total += (basketVM.Count * basketVM.Price);
                                                    }
                                                }
									<p>Sub Total <span class="text-primary">$@total.ToString("F2")</span></p>
									<p>Shipping Cost <span class="text-primary">$00.00</span></p>
									<h2>Grand Total <span class="text-primary">$@total.ToString("F2")</span></h2>

Pustok/Views/Shared/_ProductDetailPartial.cshtml
 @model Product


                    
                        <div class="row">
                            <div class="col-lg-5">
                                <!-- Product Details Slider Big Image-->
                                <div class="product-details-slider sb-slick-slider arrow-type-two" data-slick-setting='{
              "slidesToShow": 1,
              "arrows": false,
              "fade": true,
              "draggable": false,
              "swipe": false,
              "asNavFor": ".product-slider-nav"
              }'>
                                    <div class="single-slide">
                            @if (@Model.ProductImages.Count > 0)
                            {
                                <img src="image/products/@Model.ProductImages.ElementAt(0).Name" alt="">
                            }
                        </div>
                                </div>
                                <!-- Product Details Slider Nav -->
                                <div class="mt--30 product-slider-nav sb-slick-slider arrow-type-two"
                                    data-slick-setting='{
            "infinite":true,
              "autoplay": true,
              "autoplaySpeed": 8000,
              "slidesToShow": 4,
              "arrows": true,
              "prevArrow":{"buttonClass": "slick-prev","iconClass":"fa fa-chevron-left"},
              "nextArrow":{"buttonClass": "slick-next","iconClass":"fa fa-chevron-right"},
              "asNavFor": ".product-details-slider",
              "focusOnSelect": true
              }'>
                                    @*<div class="single-slide">
                                        <img src="image/products/@Model.ProductImages.ElementAt(0).Name" alt="">
                                    </div>*@
                                </div>
                            </div>
                            <div class="col-lg-7 mt--30 mt-lg--30">
                                <div class="product-details-info pl-lg--30 ">
                                    <p class="tag-block">Tags: <a href="#">Movado</a>, <a href="#">Omega</a></p>
                                    <h3 class="product-title">Beats EP Wired On-Ear Headphone-Black</h3>
                                    <ul class="list-unstyled">
                                        <li>Ex Tax: <span class="list-value"> £60.24</span></li>
                                        <li>Brands: <a href="#" class="list-value font-weight-bold"> Canon</a></li>
                                        <li>Product Code: <span class="list-value"> model1</span></li>
                                        <li>Reward Points: <span class="list-value"> 200</span></li>
                                        <li>Availability: <span class="list-value"> In Stock</span></li>
                                    </ul>
                                    <div class="price-block">
                                        <span class="price-new">£73.79</span>
                                        <del class="price-old">£91.86</del>
                                    </div>
                                    <div class="rating-widget">
                                        <div class="rating-block">
                                            <span class="fas fa-star star_on"></span>
                                            <span class="fas fa-star star_on"></span>
                                            <span class="fas fa-star star_on"></span>
                                            <span class="fas fa-star star_on"></span>
                                            <span class="fas fa-star "></span>
                                        </div>
                                        <div class="review-widget">
                                            <a href="#">(1 Reviews)</a> <span>|</span>
                                            <a href="#">Write a review</a>
                                        </div>
                                    </div>
                                    <article class="product-details-article">
                                        <h4 class="sr-only">Product Summery</h4>
                                        <p>Long printed dress with thin adjustable straps. V-neckline and wiring under
                                            the Dust with ruffles
                                            at the bottom
                                            of the
                                            dress.</p>
                                    </article>
                                    <div class="add-to-cart-row">
                                        <div class="count-input-block">
                                            <span class="widget-label">Qty</span>
                                            <input type="number" class="form-control text-center quantity" value="1">
                                        </div>
                                        <div class="add-cart-btn">
                                            <a asp-controller="Product" asp-action="AddToBasket" asp-route-id="@Model.Id" class="btn btn-outlined--primary addtobasket"><span
                                                    class="plus-icon">+</span>Add to Cart</a>
                                        </div>
                                    </div>
                                    <div class="compare-wishlist-row">
                                        <a href="#" class="add-link"><i class="fas fa-heart"></i>Add to Wish List</a>
                                        <a href="#" class="add-link"><i class="fas fa-random"></i>Add to Compare</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                

Pustok/Views/Shared/_ProductSliderPartial.cshtml
@model ICollection<Product>

<div class="product-slider multiple-row  slider-border-multiple-row  sb-slick-slider"
                                data-slick-setting='{
                            "autoplay": true,
                            "autoplaySpeed": 8000,
                            "slidesToShow": 5,
                            "rows":1,
                            "dots":true
                        }' data-slick-responsive='[
                            {"breakpoint":1200, "settings": {"slidesToShow": 3} },
                            {"breakpoint":768, "settings": {"slidesToShow": 2} },
                            {"breakpoint":480, "settings": {"slidesToShow": 1} },
                            {"breakpoint":320, "settings": {"slidesToShow": 1} }
                        ]'>
@foreach (Product product in Model)
{
    <div class="single-slide">
        <div class="product-card">
            <div class="product-header">
                <a href="#" class="author">
                    @product.Author.Name
                </a>
                <h3>
                    <a href="~/product-details.html">
                        @product.Title
                    </a>
                </h3>
            </div>
            <div class="product-card--body">
                <div class="card-image">
                    <img src="~/image/products/@product.MainImage" alt="">
                    <div class="hover-contents">
                        <a href="~/product-details.html" class="hover-image">
                            <img src="~/image/products/@product.HoverImage" alt="">
                        </a>
                        <div class="hover-btns">
                            <a href="~/cart.html" class="single-btn">
                                <i class="fas fa-shopping-basket"></i>
                            </a>
                            <a href="~/wishlist.html" class="single-btn">
                                <i class="fas fa-heart"></i>
                            </a>
                            <a href="~/compare.html" class="single-btn">
                                <i class="fas fa-random"></i>
                            </a>
                            <a id="productdetailId" asp-controller="Product" asp-action="GetDetail" asp-route-id="@product.Id" data-toggle="modal" data-target="#quickModal"
                               class="single-btn">
                                <i class="fas fa-eye"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="price-block">
                    @if (product.DiscountPrice != null)
                    {
                        <span class="price">£@(Convert.ToDouble(product.DiscountPrice).ToString("F2"))</span>
                        <del class="price-old">£@(Convert.ToDouble(product.Price.ToString("F2")))</del>
                        <span class="price-discount">@((int)(100-((product.DiscountPrice / product.Price) * 100)))%</span>
                    }
                    else
                    {
                        <span class="price">£@product.Price</span>
                    }
                </div>
            </div>
        </div>
    </div>
}
</div>